# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  push:
    branches: [ main ]


defaults:
  run:
    working-directory: ./Booking
    
jobs:
  build:
    runs-on: [self-hosted, Linux, X64, main]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      
    - run: cd ~/actions-runner/deploy/bookingApi/bookingApi/Booking
    - run: sudo docker container stop bookingContainer || true
    - run: sudo docker container stop docker-postgres || true
    - run: sudo docker container prune -f
    - run: sudo docker image rm booking || true
    - run: sudo docker build -t booking .
    - run: sudo docker run --name docker-postgres -e POSTGRES_ROOT_PASSWORD=Varun09! -e POSTGRES_DATABASE=postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=Varun09! -d postgres:alpine
    - run: sudo docker run -p 8090:8090 --name bookingContainer --link docker-postgres:postgres booking | echo "success" 
 
